# spinel: share
# The outer boxed call has only String and instance-method arms. A helper
# publishes its class ivar through an explicit class method, without readers
# or writers generated by attr_accessor.
class Payload
  class << self
    def put(value)
      @payload = value
    end

    def box
      { "payload" => @payload }
    end
  end
end

class OtherArm
  def sub(pattern, replacement)
    Payload.box
  end
end

source = String.new("https://")
Payload.put(source)

[source, OtherArm.new].each do |receiver|
  result = receiver.sub("://", "")
  if result.is_a?(Hash)
    nested = result.fetch("payload")
    puts "nested_is_source=#{nested.equal?(source)}"
    nested << "!"
  elsif result.is_a?(String)
    result << "!"
  end
end
