# Synthetic scaling program for spinel compile-time measurement.
#
#   ruby tools/compile_scale_gen.rb K > prog.rb
#
# K units, each shaped like a small slice of an application: a model-like
# class (attributes, a yielding iterator, string building), a store class
# (a hash of items, map/each_value blocks), a subclass of a shared base that
# overrides common method names (so dispatch on `area`/`describe`/`label`
# widens as K grows, as it does in a real app), and a driver that calls into
# the previous unit. The program prints a checksum; CRuby and a compiled
# binary must agree at every K.
#
# Two things scale here. Analysis: nodes and scopes both grow linearly in K.
# Emitted C: a store's items are held in an object container, which spinel
# keeps poly, so each `it.describe` / `it.count` site dispatches over EVERY
# class answering the name (2K of them) -- inline, per call site -- and the
# C grows as K^2. Real apps show the same term: inline cls_id switches are
# 11% of blog's C, 36% of campfire's, 46% of lobsters'.

frozen_forward = ARGV.delete("--frozen-forward")
k = Integer(ARGV[0] || 10)

if frozen_forward
  puts <<~RUBY
    # Force the immutable caller census, not the closed readonly certificate.
    def unused_mutator(value); value << '!'; nil; end
    class FrozenBox
      def initialize = @values = []
      def store(value); @values.push(value); nil; end
      def size = @values.size
    end
    box = FrozenBox.new
  RUBY
  k.times do |i|
    puts "def relay#{i}(box, value); box.store(value); nil; end"
    puts "def noise#{i}(value) = value + #{i}"
    puts "relay#{i}(box, 0); relay#{i}(box, 'value#{i}'); noise#{i}(#{i})"
  end
  puts "puts box.size"
  exit
end

puts <<~RUBY
  # generated by gen.rb K=#{k}
  class Shape
    def area = 0
    def label = "shape"
    def describe = "\#{label}=\#{area}"
  end

RUBY

k.times do |i|
  puts <<~RUBY
    class Item#{i}
      attr_reader :name, :count, :tags

      def initialize(name, count)
        @name = name
        @count = count
        @tags = []
      end

      def add_tag(t)
        @tags << t
        self
      end

      def each_tag
        @tags.each { |t| yield t }
      end

      def total(other)
        other.count + @count
      end

      def describe
        s = +""
        each_tag { |t| s << t << "," }
        "\#{@name}:\#{@count}:\#{s}"
      end
    end

    class Store#{i}
      def initialize
        @items = {}
      end

      def put(item)
        @items[item.name] = item
      end

      def fetch(name)
        @items[name]
      end

      def map_counts
        @items.values.map { |it| it.count * #{i % 7 + 2} }
      end

      def render
        out = []
        @items.each_value { |it| out << it.describe }
        out.join("\\n")
      end
    end

    class Shape#{i} < Shape
      def initialize(w, h)
        @w = w
        @h = h
      end

      def area = @w * @h + #{i}
      def label = "s#{i}"
    end

    def run#{i}(prev, shapes)
      st = Store#{i}.new
      3.times do |j|
        it = Item#{i}.new("n\#{j}", j + #{i})
        it.add_tag("a").add_tag("t#{i % 5}")
        st.put(it)
      end
      shapes << Shape#{i}.new(#{i % 3 + 1}, #{i % 4 + 1})
      x = st.fetch("n1")
      v = x ? x.total(prev) : 0
      [st.render.size + st.map_counts.sum + v, st.fetch("n2") || prev]
    end

  RUBY
end

puts "shapes = []"
puts "sum = 0"
puts "prev = Item0.new(\"seed\", 1)"
k.times do |i|
  puts "r = run#{i}(prev, shapes)"
  puts "sum += r[0]"
  puts "prev = Item#{(i + 1) % k}.new(\"p#{i}\", #{i}) if r[1].nil?"
end
puts <<~RUBY
  area = 0
  labels = 0
  shapes.each { |s| area += s.area; labels += s.describe.size }
  puts "k=#{k} sum=\#{sum} area=\#{area} labels=\#{labels}"
RUBY
