# Regenerates the method-name tables under src/ from the running CRuby:
#
#   ruby --disable-gems tools/gen_method_names.rb
#
#   src/core_method_names.inc           every public instance method name of a
#                                       core class or module (sorted: the
#                                       compiler binary-searches it)
#   src/object_method_names.inc         Object's instance methods, public and
#                                       private (Kernel's puts, raise, ...)
#   src/object_public_method_names.inc  Object's public instance methods
#   src/module_method_names.inc         Module's instance methods, public and
#                                       private (attr_accessor, include, ...)
core = ObjectSpace.each_object(Module).select do |m|
  n = m.name
  n && !n.include?("::") && Object.const_get(n).equal?(m) rescue false
end
names = core.flat_map(&:public_instance_methods).map(&:to_s).uniq.sort
obj_all = (Object.instance_methods + Object.private_instance_methods).map(&:to_s).uniq.sort
obj_pub = Object.public_instance_methods.map(&:to_s).uniq.sort
mod_all = (Module.instance_methods + Module.private_instance_methods).map(&:to_s).uniq.sort

def emit(path, header, list)
  File.write(path, "/* #{header} CRuby #{RUBY_VERSION}. Generated by tools/gen_method_names.rb. */\n" +
                   list.map { |n| "  #{n.dump},\n" }.join)
end
dir = File.expand_path("../src", __dir__)
emit("#{dir}/core_method_names.inc",
     "Every public instance method name of a core class or module, sorted.", names)
emit("#{dir}/object_method_names.inc",
     "Object's instance method names, public and private.", obj_all)
emit("#{dir}/object_public_method_names.inc", "Object's public instance method names.", obj_pub)
emit("#{dir}/module_method_names.inc", "Module's instance method names, public and private.", mod_all)
